### ISSUE TITLE
Damm algorithm

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/30-seconds-of-java#114]
In error detection, the Damm algorithm is a check digit algorithm that detects all single-digit errors and all adjacent transposition errors.

https://en.wikipedia.org/wiki/Damm_algorithm

**Comment by hikmet-cakir** [comment]
I would like to work on this issue if it is still available.

**Comment by AddeusExMachina** [comment]
Hi, I implemented three snippets of the Damm algorithm validation.
1. Traditional for loop
```java
  boolean damm(String s) {
    int row = 0;
    for (int i = 0; i < s.length(); i++) {
      row = table[row][s.charAt(i) - '0'];
    }
    return row == 0;
  }
```
2. Enhanced for loop
```java
  boolean damm(String s) {
    int row = 0;
    for (var c : s.toCharArray()) {
      row = table[row][c - '0'];
    }
    return row == 0;
  }
```
3. Stream
```java
  boolean damm(String s) {
    return s.chars().reduce(0, (row, col) -> table[row][col - '0']) == 0;
  }
```

**Comment by nour-awad** [comment]
@iluwatar can you assign me to this issue?
