### ISSUE TITLE
Create CI build

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/30-seconds-of-java#124]
To make it easier to quality control the incoming pull requests, we should have a CI build.

Acceptance criteria

- Github Actions based CI-build has been created
- Builds the main branch when it changes
- Incoming pull requests are checked

**Comment by RohitPatel1122** [comment]
Is this still needed ? Since we have CI in place

**Comment by iluwatar** [comment]
I'll close this issue as fixed
