### ISSUE TITLE
Upgrade Checkstyle

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/30-seconds-of-java#125]
The project currently uses a custom checkstyle configuration in config/checkstyle.xml. In this task let's upgrade Checkstyle and start using the built-in Google checks instead of a custom configuration.

Acceptance criteria

- Checkstyle updated to the latest version
- Checkstyle uses Google checks instead of the custom config

**Comment by klurpicolo** [comment]
Hi👋, I'd like to work on this.

**Comment by iluwatar** [comment]
Ok @klurpicolo
