### ISSUE TITLE
Add Array Algorithms

### ISSUE THREAD

**Issue by vaibhavpriyatosh** [iluwatar/30-seconds-of-java#131]
I would like to add more algorithms in Array section.

**Comment by iluwatar** [comment]
Sounds good. Go ahead @vaibhavpriyatosh

**Comment by vedantzope9** [comment]
Is anyone working on it? I want to contribute and add more algorithms

**Comment by iluwatar** [comment]
@vaibhavpriyatosh are you still active with this? If not, I'll assign it to @vedantzope9

**Comment by SumanohariR** [comment]
Hello, I hope you're all doing well! I'm a newcomer, and I think I have the required abilities to solve this issue. Could you please confirm whether this issue has already been assigned to someone? If it hasn't it would be a pleasure to contribute to your project!

**Comment by iluwatar** [comment]
Assigned to @vedantzope9
