### ISSUE TITLE
Add new solutions to fibonacci and factorial

### ISSUE THREAD

**Issue by AndreLucasrs** [iluwatar/30-seconds-of-java#139]
I would like to add a new iterative fibonacci solution and a recursion factorial solution

**Comment by iluwatar** [comment]
Sounds good @AndreLucasrs, please go ahead

**Comment by AndreLucasrs** [comment]
[PR](https://github.com/iluwatar/30-seconds-of-java/pull/140)

**Comment by AndreLucasrs** [comment]
Could you add the Hacktoberfest information ? 
because it was not accounted for

**Comment by iluwatar** [comment]
The repository has the `hacktoberfest` label so I think it should be counted in
