### ISSUE TITLE
Need help with Korean translation

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/30-seconds-of-java#147]
To show the code snippets correctly on the Korean website, we need a translation of README.md. The result of the translation should be placed to localization/ko/README.md.

Acceptance criteria

- README.md translated to Korean

**Comment by jso4342** [comment]
I've translated a pull request for translated README.md in Korean! 
Hopefully it's helpful :)

**Comment by iluwatar** [comment]
Thank you so much for providing this. It's now available on the website too, see https://java-design-patterns.com/ko/snippets/
