### ISSUE TITLE
HttpPostSnippetTest.testHttpPost failing

### ISSUE THREAD

**Issue by alidehkhodaei** [iluwatar/30-seconds-of-java#163]
Hello, In the HttpPostSnippetTest class, the testHttpPost method is failing. This method is intended to test the behavior of an HTTP POST request, but it's currently failing for some reason.

**Comment by iluwatar** [comment]
Fixed in https://github.com/iluwatar/30-seconds-of-java/commit/4d1b9d4cc9560f7baa5b37d6069c445e48a79b88
