### ISSUE TITLE
Would like to add some more math snippets

### ISSUE THREAD

**Issue by srijitt** [iluwatar/30-seconds-of-java#191]
I would like to add some more basic snippets like decimal to binary conversion, binary to decimal conversion, armstrong number, etc. This would enhance the overall value of the repository, as many beginners start with solving such basic problems like armstrong numbers, happy numbers, bin2dec conversion and vice-versa.

**Comment by iluwatar** [comment]
Sounds good @srijitt, please go ahead

**Comment by srijitt** [comment]
Added 2 snippets, and made a PR. Do check it out kindly.

**Comment by GeriMultiDev** [comment]
Hello, how are you?
First of all, I want to say that I'm new to GitHub and I still don't fully understand how it works, but if I can contribute to this task, I would be willing to work on it. I would need some guidance if it's not too much trouble.
Thank you

**Comment by iluwatar** [comment]
Hey @GeriMultiDev, welcome! I'll close this issue as completed, but please feel free to create another for yourself explaining your idea. See also https://github.com/iluwatar/30-seconds-of-java/blob/master/CONTRIBUTE.md
