### ISSUE TITLE
Lindenmayer (L-system) function

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/30-seconds-of-java#214]
#### Description
We need to implement the Lindenmayer system (L-system) algorithm for generating strings based on predefined production rules. This algorithm should be designed with modularity and scalability in mind, adhering to best practices in software design and architecture. The implementation should be clean, efficient, and well-documented, aligning with our project's contribution guidelines.

The L-system algorithm is well-documented in various sources:
- [Wikipedia: Lindenmayer System](https://en.wikipedia.org/wiki/L-system)
- "The Algorithmic Beauty of Plants" by Przemyslaw Prusinkiewicz and Aristid Lindenmayer
- [GeeksforGeeks: Introduction to L-systems](https://www.geeksforgeeks.org/introduction-to-l-systems/)

#### Key Requirements
- Develop a function to generate strings using the Lindenmayer system.
- The function should accept an initial string (axiom), a set of production rules, and the number of iterations as input parameters.
- Ensure the function handles the parallel rewriting of symbols according to the production rules.
- Include comprehensive unit tests to validate the correctness of the algorithm.
- Provide clear documentation for the function, including usage examples.

#### Acceptance Criteria
1. The implemented function correctly generates L-system strings based on the given axiom, production rules, and iterations.
2. The implementation follows the project's contribution guidelines and best practices in software design.
3. The code is covered by unit tests that verify its correctness under various scenarios and edge cases.

[Contribution Guidelines](https://github.com/iluwatar/30-seconds-of-java/blob/master/CONTRIBUTE.md)

**Comment by SayedQassim** [comment]
Hi @iluwatar, I will take care of this.
