### ISSUE TITLE
Elo rating

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/30-seconds-of-java#34]
Provide snippet that calculates Elo rating https://en.wikipedia.org/wiki/Elo_rating_system

**Comment by draco-malfoy** [comment]
Should i take this? @iluwatar

**Comment by iluwatar** [comment]
Sure @draco-malfoy, go ahead!

**Comment by dchar** [comment]
@iluwatar It didn't look like this was ever completed, so I finished an implementation of my own today. Please let me know if it's still relevant!

**Comment by iluwatar** [comment]
It's not implemented yet
