### ISSUE TITLE
Luhn algorithm

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/30-seconds-of-java#35]
Luhn algorithm is used to validate a variety of identification numbers https://en.wikipedia.org/wiki/Luhn_algorithm

**Comment by MaVdbussche** [comment]
I would like to work on this issue if it is still available.

**Comment by iluwatar** [comment]
Ok @MaVdbussche

**Comment by iluwatar** [comment]
Ok, assigned to @soer-robin
