### ISSUE TITLE
Levenshtein distance

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/30-seconds-of-java#37]
Provide snippet that calculates Levenshtein distance https://en.wikipedia.org/wiki/Levenshtein_distance

**Comment by raja-peeyush-kumar-singh** [comment]
I would like to work on this one, if this one has not been picked up.

**Comment by iluwatar** [comment]
@raja-peeyush-kumar-singh thanks, please go ahead

**Comment by raja-peeyush-kumar-singh** [comment]
Pull request has passed the checks, please merge or let me know if something needs change
